{{- if .Values.certManager.enabled }}
{{- if .Values.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  namespace: {{ include "toolhive-webhook.namespace" . }}
  labels:
    {{- include "toolhive-webhook.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}
