{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "toolhive-webhook.fullname" . }}-mutating-webhook-configuration
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "toolhive-webhook.namespace" . }}/{{ include "toolhive-webhook.fullname" . }}-serving-cert
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "toolhive-webhook.fullname" . }}-webhook-service
      namespace: {{ include "toolhive-webhook.namespace" . }}
      path: /mutate-toolhive-stacklok-dev-v1alpha1-mcpserver
  failurePolicy: Fail
  name: mmcpserver-v1alpha1.kb.io
  rules:
  - apiGroups:
    - toolhive.stacklok.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mcpservers
  sideEffects: None
{{- end }}
